LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := GoogleCameraModPixel2
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := GCam-5.1.018-Pixel2Mod-Arnova8G2-V8.3b1.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
include $(BUILD_PREBUILT)
